#!/bin/sh

# Set up the configuration for the Lighthouse Debian Live OS
# We use XFCE for a very lightweight desktop environment

TARGET_ARCH=${LB_ARCHITECTURE:-amd64}

lb config noauto \
    --mode debian \
    --system live \
    --architectures "$TARGET_ARCH" \
    --linux-flavours "$TARGET_ARCH" \
    --distribution bookworm \
    --archive-areas "main contrib non-free non-free-firmware" \
    --apt-indices false \
    --apt-recommends false \
    --bootappend-live "boot=live components quiet splash systemd.show_status=false loglevel=3" \
    "${@}"
